/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class App {
  public static void main(String[] args) throws Exception {
    //////////////////////////////////// challenge 10 ///////////////////////////////////
    ////////////////Stack/////////////////
    //push
//    Stack<Integer> st1 = new Stack<>();
//    st1.push(1);
//    st1.push(2);
//    st1.push(3);
//    System.out.println(st1.top.value);
//    System.out.println(st1.top.next.value);

    //pop
//    try {
//      System.out.println(st1.pop());
//      System.out.println(st1.top.value);
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    }

    //peek
//    try {
//      System.out.println(st1.peek());
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    }
//    //is empty
//    System.out.println(st1.isEmpty());

    ////////////////Queue/////////////////
    //enqueue
//    Queue<String> q1 = new Queue<>();
//    q1.enqueue("a");
//    q1.enqueue("b");
//    q1.enqueue("c");
//    System.out.println(q1.front.value);
//    System.out.println(q1.rear.value);
    //dequeue
//    try {
//      System.out.println(q1.dequeue());
//      System.out.println(q1.front.value);
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    }
    //peek
//    try {
//      System.out.println(q1.peek());
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    }
    //is empty
//    System.out.println(q1.isEmpty());

    //////////////////////////////////// challenge 11 ///////////////////////////////////
    //enqueue
    PseudoQueue<Integer> pq1 = new PseudoQueue<>();
    pq1.enqueue(20);
    pq1.enqueue(15);
    pq1.enqueue(10);
    pq1.enqueue(5);

    System.out.println(pq1.toString());
    //dequeue
    pq1.dequeue();
    System.out.println(pq1.toString());
    pq1.dequeue();
    System.out.println(pq1.toString());
  }
}
