/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SinglyLinkedLists;

public class App {

  public static void main(String[] args) {
    LinkedList list1 = new LinkedList();
    // insert
    list1.insert(1);
    list1.insert(2);
    list1.insert(3);
    list1.insert(50);
    list1.insert(4);
    list1.insert(100);
    list1.insert(300);
    // see the list
    Node current = list1.head;
    while (current != null) { // if i didn't reach the end of the list
      System.out.println(current.data);
      current = current.next;
    }

    //includes
    System.out.println(list1.includes(300));

    // to string
    System.out.println(list1.toStr());
  }
}
