/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import java.util.Arrays;

public class App {
  ////////////////////////////////////// Challenge: 26 //////////////////////////////////////
  public static int[] selectionSort(int[] arr) {
    for (int i = 0; i < arr.length + 1; i++) {
      for (int j = i + 1; j < arr.length; j++) {
        if (arr[j] < arr[i]) {
          int num = arr[i];
          arr[i] = arr[j];
          arr[j] = num;
        }
      }
    }
    return arr;
  }

  public static int[] insertionSort(int[] arr) {
    for (int i = 1; i < arr.length; i++) {
      int j = i - 1;
      int temp = arr[i];

      while (j >= 0 && temp < arr[j]) {
        arr[j + 1] = arr[j];
        j = j - 1;
      }
      arr[j + 1] = temp;
    }
    return arr;
  }

  public static void main(String[] args) {
    // normal case
    int[] arr = {8, 4, 23, 42, 16, 15};
    // Reverse-sorted
    int[] arr2 = {20, 18, 12, 8, 5, -2};
    // Nearly-sorted
    int[] arr3 = {2, 3, 5, 7, 13, 11};
    // Few uniques
    int[] arr4 = {5, 12, 7, 5, 5, 7};
    System.out.println(Arrays.toString(insertionSort(arr)));
    System.out.println(Arrays.toString(insertionSort(arr2)));
    System.out.println(Arrays.toString(insertionSort(arr3)));
    System.out.println(Arrays.toString(insertionSort(arr4)));
  }
}
