/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

public class App {
    public static void main(String[] args) {
      //////////////////////////////////////// lab 35 /////////////////////////////////////////
      Graph graph = new Graph();
      graph.addNode("Bob");
      graph.addNode("Alice");
      graph.addNode("Mark");
      graph.addNode("Rob");
      graph.addNode("Maria");
      graph.addEdge("Bob", "Alice");
      graph.addEdge("Bob", "Rob");
      graph.addEdge("Alice", "Mark");
      graph.addEdge("Rob", "Mark");
      graph.addEdge("Alice", "Maria");
      graph.addEdge("Rob", "Maria");

      System.out.println(graph.getNodes());
      System.out.println(graph.getNeighbors("Bob"));
      System.out.println(graph.size());
    }
}
