/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  ////////////////////////////////////// Challenge: 26 //////////////////////////////////////
    @Test void insertionSort1() {
      int[] arr = {8, 4, 23, 42, 16, 15};
      // output must be
      int[] out =  {4, 8, 15, 16, 23, 42};

      assertEquals(Arrays.toString(out), Arrays.toString(App.insertionSort(arr)));
    }

  @Test void insertionSort2() {
    int[] arr = {5, 12, 7, 5, 5, 7};
    // output must be
    int[] out =  {5, 5, 5, 7, 7, 12};

    assertEquals(Arrays.toString(out), Arrays.toString(App.insertionSort(arr)));
  }

  ////////////////////////////////////// Challenge: 27 //////////////////////////////////////
  @Test void mergeSort1() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    // output must be
    int[] out =  {4, 8, 15, 16, 23, 42};

    assertEquals(Arrays.toString(out), Arrays.toString(App.mergeSort(arr)));
  }

  @Test void mergeSort2() {
    int[] arr = {5, 12, 7, 5, 5, 7};
    // output must be
    int[] out =  {5, 5, 5, 7, 7, 12};

    assertEquals(Arrays.toString(out), Arrays.toString(App.mergeSort(arr)));
  }

  ////////////////////////////////////// Challenge: 28 //////////////////////////////////////

  @Test void quickSort1() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    // output must be
    int[] out =  {4, 8, 15, 16, 23, 42};

    assertEquals(Arrays.toString(out), Arrays.toString(App.quickSort(arr,0,5)));
  }

  @Test void quickSort2() {
    int[] arr = {5, 12, 7, 5, 5, 7};
    // output must be
    int[] out =  {5, 5, 5, 7, 7, 12};

    assertEquals(Arrays.toString(out), Arrays.toString(App.quickSort(arr,0,5)));
  }

}
