/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash.table;

public class App {

    public static void main(String[] args) {
  ///////////////////////////////////// challenge 30 ////////////////////////////////////
      HashTable<String> hashTable = new HashTable<>(10);

      hashTable.add(11,"ahmad");
      hashTable.add(12,"osama");
      hashTable.add(12,"ibrahim");

      System.out.println(hashTable.get(12));
      System.out.println(hashTable.contains(11));
    }
}
